const kittens: Array<KittenSchema> = [
  {
    id: 1,
    model: 'kitten',
    name: 'Fluffy',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'White',
    eyeColor: 'Blue',
    dob: '2023-01-01',
    description: 'Adorable and playful kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Available',
    breed: 'Persian',
    price: 500,
  },
  {
    id: 2,
    model: 'kitten',
    name: 'Whiskers',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Tabby',
    eyeColor: 'Green',
    dob: '2023-02-15',
    description: 'Curious and friendly kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Sold',
    breed: 'Maine Coon',
    price: 700,
  },
  {
    id: 3,
    model: 'kitten',
    name: 'Mittens',
    gender: 'TBD',
    ears: 'TBD',
    furColor: 'Black and White',
    eyeColor: 'Hazel',
    dob: '2023-03-20',
    description: 'Playful and mischievous kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Reserved',
    breed: 'Siamese',
    price: 600,
  },
  {
    id: 4,
    model: 'kitten',
    name: 'Milo',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Gray',
    eyeColor: 'Amber',
    dob: '2023-04-01',
    description: 'Playful and energetic kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Available',
    breed: 'Maine Coon',
    price: 600,
  },
  {
    id: 5,
    model: 'kitten',
    name: 'Coco',
    gender: 'Girl',
    ears: 'Fold',
    furColor: 'Chocolate',
    eyeColor: 'Green',
    dob: '2023-03-10',
    description: 'Sweet and affectionate kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Available',
    breed: 'Persian',
    price: 800,
  },
  {
    id: 6,
    model: 'kitten',
    name: 'Whiskey',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Orange',
    eyeColor: 'Blue',
    dob: '2023-02-20',
    description: 'Adventurous and curious kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Available',
    breed: 'Siamese',
    price: 500,
  },
  {
    id: 7,
    model: 'kitten',
    name: 'Lily',
    gender: 'Girl',
    ears: 'TBD',
    furColor: 'Calico',
    eyeColor: 'Hazel',
    dob: '2023-03-15',
    description: 'Graceful and gentle kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Reserved',
    breed: 'Persian',
    price: 700,
  },
  {
    id: 8,
    model: 'kitten',
    name: 'Oliver',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Cream',
    eyeColor: 'Green',
    dob: '2023-01-25',
    description: 'Charming and playful kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Reserved',
    breed: 'Maine Coon',
    price: 900,
  },
  {
    id: 9,
    model: 'kitten',
    name: 'Mia',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Black',
    eyeColor: 'Amber',
    dob: '2023-02-05',
    description: 'Elegant and independent kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Reserved',
    breed: 'Siamese',
    price: 650,
  },
  {
    id: 10,
    model: 'kitten',
    name: 'Simba',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Orange',
    eyeColor: 'Blue',
    dob: '2023-01-12',
    description: 'Brave and friendly kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Sold',
    breed: 'Persian',
    price: 750,
  },
  {
    id: 11,
    model: 'kitten',
    name: 'Lola',
    gender: 'Girl',
    ears: 'TBD',
    furColor: 'Tabby',
    eyeColor: 'Green',
    dob: '2023-03-05',
    description: 'Playful and mischievous kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Sold',
    breed: 'Maine Coon',
    price: 850,
  },
  {
    id: 12,
    model: 'kitten',
    name: 'Max',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Gray and White',
    eyeColor: 'Amber',
    dob: '2023-02-15',
    description: 'Loyal and intelligent kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Sold',
    breed: 'Siamese',
    price: 550,
  },
  {
    id: 13,
    model: 'kitten',
    name: 'Milo',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Gray',
    eyeColor: 'Amber',
    dob: '2023-04-01',
    description: 'Playful and energetic kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Available',
    breed: 'Maine Coon',
    price: 600,
  },
  {
    id: 14,
    model: 'kitten',
    name: 'Coco',
    gender: 'Girl',
    ears: 'Fold',
    furColor: 'Chocolate',
    eyeColor: 'Green',
    dob: '2023-03-10',
    description: 'Sweet and affectionate kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Available',
    breed: 'Persian',
    price: 800,
  },
  {
    id: 15,
    model: 'kitten',
    name: 'Whiskey',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Orange',
    eyeColor: 'Blue',
    dob: '2023-02-20',
    description: 'Adventurous and curious kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Available',
    breed: 'Siamese',
    price: 500,
  },
  {
    id: 16,
    model: 'kitten',
    name: 'Lily',
    gender: 'Girl',
    ears: 'TBD',
    furColor: 'Calico',
    eyeColor: 'Hazel',
    dob: '2023-03-15',
    description: 'Graceful and gentle kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Samantha',
    father: 'Max',
    status: 'Reserved',
    breed: 'Persian',
    price: 700,
  },
  {
    id: 17,
    model: 'kitten',
    name: 'Oliver',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Cream',
    eyeColor: 'Green',
    dob: '2023-01-25',
    description: 'Charming and playful kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Reserved',
    breed: 'Maine Coon',
    price: 900,
  },
  {
    id: 18,
    model: 'kitten',
    name: 'Mia',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Black',
    eyeColor: 'Amber',
    dob: '2023-02-05',
    description: 'Elegant and independent kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Reserved',
    breed: 'Siamese',
    price: 650,
  },
  {
    id: 19,
    model: 'kitten',
    name: 'Bella',
    gender: 'Girl',
    ears: 'Fold',
    furColor: 'Tortoiseshell',
    eyeColor: 'Green',
    dob: '2023-02-18',
    description: 'Playful and friendly kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Luna',
    father: 'Leo',
    status: 'Sold',
    breed: 'Maine Coon',
    price: 950,
  },
  {
    id: 20,
    model: 'kitten',
    name: 'Charlie',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Gray and White',
    eyeColor: 'Amber',
    dob: '2023-03-08',
    description: 'Adventurous and cuddly kitten',
    isHidden: false,
    isAdminHidden: false,
    mother: 'Coco',
    father: 'Oscar',
    status: 'Sold',
    breed: 'Siamese',
    price: 600,
  },
];

const dams: Array<AdultCatSchema> = [
  {
    id: 101,
    model: 'dam',
    name: 'Fluffy',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'White',
    eyeColor: 'Blue',
    dob: '2019-05-01',
    description: 'Gentle and caring',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'Persian',
    mainImageSrcValue: '/images/fluffy.jpg',
    regNum: 12345,
  },
  {
    id: 102,
    model: 'dam',
    name: 'Misty',
    gender: 'Girl',
    ears: 'Fold',
    furColor: 'Cream',
    eyeColor: 'Green',
    dob: '2020-08-10',
    description: 'Playful and affectionate',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'Scottish Fold',
    mainImageSrcValue: '/images/misty.jpg',
    regNum: 54321,
  },
  {
    id: 103,
    model: 'dam',
    name: 'Luna',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Black',
    eyeColor: 'Yellow',
    dob: '2018-12-05',
    description: 'Independent and graceful',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'Siamese',
    mainImageSrcValue: '/images/luna.jpg',
    regNum: null,
  },
];

const sires: Array<AdultCatSchema> = [
  {
    id: 201,
    model: 'sire',
    name: 'Whiskers',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Orange',
    eyeColor: 'Green',
    dob: '2017-09-20',
    description: 'Friendly and playful',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'Maine Coon',
    mainImageSrcValue: '/images/whiskers.jpg',
    regNum: 98765,
  },
  {
    id: 202,
    model: 'sire',
    name: 'Leo',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Tabby',
    eyeColor: 'Amber',
    dob: '2018-03-15',
    description: 'Laid-back and affectionate',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'Scottish Fold',
    mainImageSrcValue: '/images/leo.jpg',
    regNum: 87654,
  },
  {
    id: 203,
    model: 'sire',
    name: 'Max',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Black',
    eyeColor: 'Blue',
    dob: '2016-07-10',
    description: 'Curious and adventurous',
    isHidden: false,
    isAdminHidden: false,
    status: 'Active',
    breed: 'British Shorthair',
    mainImageSrcValue: '/images/max.jpg',
    regNum: 65432,
  },
];

export { kittens, dams, sires };
