import './globalCSS/main_layout_components/main.css';
import { Cinzel } from 'next/font/google';
import { NextFont } from 'next/dist/compiled/@next/font';

import Header from './_layout_components/Header';
import Footer from './_layout_components/Footer';

type RootLayoutProps = {
  children: React.ReactNode;
};

const cinzel: NextFont = Cinzel( {
  subsets: ['latin'],
  display: 'swap',
  style: ['normal'],
  weight: ['400', '500', '700'],
} );

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout( { children }: RootLayoutProps ): JSX.Element {
  return (
    <html lang="en">
      <body className={ cinzel.className }>
        <div
          id="App"
          className="App"
        >
          <Header />
          <div className="pages-container">
            { children }
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
