import './globalCSS/main_layout_components/main.css'
import { Cinzel} from 'next/font/google'

import Header from './(layout_components)/Header'
import Footer from './(layout_components)/Footer'

const cinzel = Cinzel({ 
  subsets: ['latin'], 
  display: 'swap', 
  style: [ 'normal',],
  weight: ['400', '500', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
        <div id='App' className='App'>
          <Header />
          <div >
          {/* {children} */}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
