import styles from './layout.module.css';

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: LayoutProps): JSX.Element {
  return (
    <div className={styles.layout_wrapper}>
      {children}
    </div>
  );
}
